name: hankstoremanager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - sqlite
  - sqlcipher
  - pysqlcipher3
  - pyinstaller
  - cryptography
  - python-dotenv
  # Windows-only packages (msys2 utile pour libsqlcipher sur Windows)
  - msys2  # [win]
  # Ajoute d'autres paquets Windows-only ici avec # [win] si n√©cessaire
