name: hankstoremanager
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - sqlite
  - sqlcipher
  - pysqlcipher3
  - pyinstaller
  - cryptography
  - python-dotenv
  - msys2  # [win]
  - pip:
    - -r requirements.txt
